require:
  - rubocop/cop/memox

Memox/MethodDefinition:
  Description: "Disallows the use of `memoize` without a method definition"
  Enabled: true

Memox/MethodSignature:
  Description: "Disallows the use of `memoize` for methods that accept arguments"
  Enabled: true
